import type { Metadata } from "next";
import "./globals.css";
import NavbarFooterWrapper from "@/components/NavbarFooterWrapper"; // Se decidio asi por 2 errores

export const metadata: Metadata = {
  title: "HappyPaws",
  description: "Generated by HappyPaws",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <NavbarFooterWrapper>{children}</NavbarFooterWrapper>
      </body>
    </html>
  );
}
